### ISSUE TITLE
question on unl2003+stepper.

### ISSUE THREAD

**Issue by exilaus** [nanpy/nanpy#13]
Ciao,
i write this piece of code for pilot a little  28BJY-48 stepper with uln2003, but execute is very slow generaly on rpi gpio or in arduino firmware is really fast and need add a delay for no lose steps.

As you can see, i work on windows (autodetection no work) but forcing connection on right com nanpy work very fine.
Any suggestion? need write firmware module for this use?(i need can execute a code after/before any phase)

have nice day e buon anno.
Mauro.

from nanpy import Arduino
from nanpy import serial_manager
serial_manager.connect('COM11')

Arduino.pinMode(2, Arduino.OUTPUT)
Arduino.pinMode(3, Arduino.OUTPUT)
Arduino.pinMode(4, Arduino.OUTPUT)
Arduino.pinMode(5, Arduino.OUTPUT)
for x in range(0,512):
   #phase n0------------------------------
   Arduino.digitalWrite(5, Arduino.HIGH)
   Arduino.digitalWrite(4, Arduino.LOW)
   Arduino.digitalWrite(3, Arduino.LOW)
   Arduino.digitalWrite(2, Arduino.LOW)
   #Arduino.delay(2)
   #phase n1------------------------------
   Arduino.digitalWrite(5, Arduino.HIGH)
   Arduino.digitalWrite(4, Arduino.HIGH)
   Arduino.digitalWrite(3, Arduino.LOW)
   Arduino.digitalWrite(2, Arduino.LOW)
   #Arduino.delay(2)
   #phase n2----------------------------- 
   Arduino.digitalWrite(5, Arduino.LOW)
   Arduino.digitalWrite(4, Arduino.HIGH)
   Arduino.digitalWrite(3, Arduino.LOW)
   Arduino.digitalWrite(2, Arduino.LOW)
   #Arduino.delay(2)
   #phase n3-----------------------------
   Arduino.digitalWrite(5, Arduino.LOW)
   Arduino.digitalWrite(4, Arduino.HIGH)
   Arduino.digitalWrite(3, Arduino.HIGH)
   Arduino.digitalWrite(2, Arduino.LOW)
   #Arduino.delay(2)
   #phase n4-----------------------------
   Arduino.digitalWrite(5, Arduino.LOW)
   Arduino.digitalWrite(4, Arduino.LOW)
   Arduino.digitalWrite(3, Arduino.HIGH)
   Arduino.digitalWrite(2, Arduino.LOW)
   #Arduino.delay(2)
   #phase n5-----------------------------
   Arduino.digitalWrite(5, Arduino.LOW)
   Arduino.digitalWrite(4, Arduino.LOW)
   Arduino.digitalWrite(3, Arduino.HIGH)
   Arduino.digitalWrite(2, Arduino.HIGH)
   #Arduino.delay(2)
   #phase n6-----------------------------
   Arduino.digitalWrite(5, Arduino.LOW)
   Arduino.digitalWrite(4, Arduino.LOW)
   Arduino.digitalWrite(3, Arduino.LOW)
   Arduino.digitalWrite(2, Arduino.HIGH)
   #Arduino.delay(2)
   #phase n7-----------------------------
   Arduino.digitalWrite(5, Arduino.HIGH)
   Arduino.digitalWrite(4, Arduino.LOW)
   Arduino.digitalWrite(3, Arduino.LOW)
   Arduino.digitalWrite(2, Arduino.HIGH)
   #Arduino.delay(2)

**Comment by sebcorse** [comment]
Hello
I have the same problem
The lib for arduino is called AccelStepper.h, and work perfectly when used direcly on arduino
Is it a way to include it in Nanpy so that I can control from python ?

Thanks for your help
