### ISSUE TITLE
servos conflict

### ISSUE THREAD

**Issue by electronshic** [nanpy/nanpy#15]
Using 2 or more servos in 1 loop causes serial timeout error.
Traceback (most recent call last):
  File "../nanpy-master/nanpy_test.py", line 205, in <module>
    servo1.write(15)
  File "../nanpy-master/nanpy/arduinoboard.py", line 68, in wrapper
    return _call(self.namespace, self.id, call_pars, connection=connection)
  File "../nanpy-master/nanpy/arduinoboard.py", line 46, in _call
    ret = return_value(connection)
  File "../nanpy-master/nanpy/arduinoboard.py", line 18, in return_value
    return serial_manager.readline().replace('\r\n', '')
  File "../nanpy-master/nanpy/serialmanager.py", line 88, in readline
    raise SerialManagerError('Serial timeout!')
nanpy.serialmanager.SerialManagerError: Serial timeout!

in loops servos turn in one way. But if servos turn back this error causes.
Is there any correct way to move servos in different directions without errors? One servo does not cause the error.

**Comment by astagi** [comment]
updates?

**Comment by astagi** [comment]
@ponty @electronshic I've just bought a new servo motor so I can make some test and see what happens :)

**Comment by astagi** [comment]
It works perfectly with two servos, maybe something changed during these months :) This is the code I tested (please read carefully http://arduino.cc/en/reference/servo and use an external power supply):

    from nanpy import Servo
    from nanpy import SerialManager
    import time
    connection = SerialManager(device='/dev/cu.usbmodem1411')

    servo1 = Servo(7, connection=connection)
    servo2 = Servo(3, connection=connection)
    for move in [0, 90, 180, 90, 0]:
        servo1.write(move)
        time.sleep(1)
        servo2.write(move)
