### ISSUE TITLE
nanpy + bluetooth

### ISSUE THREAD

**Issue by electronshic** [nanpy/nanpy#17]
Hello!
Could you help me with bluetooth and nanpy connection to arduino?
How to set /dev/rfcomm* serial port in nanpy? Do i need to do that?

Arduino works with sketch:
```c
#include <SoftwareSerial.h>

#define RxD 0    //receive data on digital 0
#define TxD 1 //transmit on digital 1

SoftwareSerial blueToothSerial(RxD, TxD);
int counter = 0;
int incoming;
void setup(void){
  Serial.begin(9600);
  //pinMode(RxD,INPUT);
  //pinMode(TxD,OUTPUT);
  setupBlueToothConnection();
}

void setupBlueToothConnection(){
  blueToothSerial.begin(19200);
  blueToothSerial.print("\r\n+STWMOD=0\r\n"); //set the bluetooth work in slave mode
  blueToothSerial.print("\r\n+STNA=SeeedBTSlave\r\n"); //set the bluetooth name as     "SeeedBTSlave"
  blueToothSerial.print("\r\n+STOAUT=1\r\n"); // Permit Paired device to connect me
  //blueToothSerial.print("\r\n+STAUTO=0\r\n"); // Auto-connection should be forbidden here
  delay(2000); // This delay is required.
  blueToothSerial.print("\r\n+INQ=1\r\n"); //make the slave bluetooth inquirable
  Serial.println("The slave bluetooth is inquirable!");
  delay(2000); // This delay is required.
  blueToothSerial.flush();
} 

void loop(){
  if(blueToothSerial.available())
     Serial.println(blueToothSerial.read());
  blueToothSerial.write('x');
}
```
...and python code:
```python
from bluetooth import *
import sys
bd_addr = "20:13:08:16:08:72" #itade address

port = 1
sock=BluetoothSocket( RFCOMM )
print(sock)
sock.connect((bd_addr, port))
print 'Connected'
sock.settimeout(1.0)
sock.send("x")
print 'Sent data'

data = sock.recv(1)
print 'received [%s]'%data

sock.close()
```
But i can not make nanpy code to work with bluetooth serial port. I tryed synclock.py example but nothing works too. Says that can not open serial port.

Ubuntu 13.04 x64
Python 2.7.4
Arduino Nano v3.0

**Comment by Pi3R1k** [comment]
I make some test with nanpy and bluetooth module hc-06 (slave only). Work nice but need to add `+ glob.glob('/dev/rfcomm*')` in **serialmanager.py** and connect bluetooth module to RX(0)/TX(1).

**Comment by astagi** [comment]
Oh wow sounds great! Which kind (model/vendor) of Arduino module are you using? 
Can you try using SerialManager? something like:

    from nanpy import (ArduinoApi, SerialManager)
    from time import sleep

    connection = SerialManager('/dev/rfcomm0')
    a = ArduinoApi(connection=connection)

    a.pinMode(13, a.OUTPUT)

    for i in range(10000):
        a.digitalWrite(13, (i + 1) % 2)
        sleep(0.2)

Let me know, thank you!

**Comment by Pi3R1k** [comment]
hc-06 is a cheap bluetooth module bought on ebay. Here is a doc : http://www.rcscomponents.kiev.ua/datasheets/hc_hc-05-user-instructions-bluetooth.pdf

- hc-06 work only in slave mode
- hc-05 work in master or slave mode

when i use SerialManager directry without modifying SerialManager.py, i have this error : 
```
Traceback (most recent call last):
  File "./plc_cro.py", line 29, in <module>
    sensors = DallasTemperature(2)
  File "/usr/lib/python2.7/site-packages/nanpy/dallastemperature.py", line 9, in __init__
    self.id = self.call('new', pin)
  File "/usr/lib/python2.7/site-packages/nanpy/arduinoboard.py", line 150, in call
    return _call(self.namespace, self.id, args, self.connection)
  File "/usr/lib/python2.7/site-packages/nanpy/arduinoboard.py", line 28, in _call
    _write(namespace, connection)
  File "/usr/lib/python2.7/site-packages/nanpy/arduinoboard.py", line 11, in _write
    serial_manager.write('%s\0' % str(data))
  File "/usr/lib/python2.7/site-packages/nanpy/serialmanager.py", line 84, in write
    self.open()
  File "/usr/lib/python2.7/site-packages/nanpy/serialmanager.py", line 77, in open
    timeout=self.timeout)
  File "/usr/lib/python2.7/site-packages/serial/serialutil.py", line 282, in __init__
    self.open()
  File "/usr/lib/python2.7/site-packages/serial/serialposix.py", line 289, in open
    self.fd = os.open(self.portstr, os.O_RDWR|os.O_NOCTTY|os.O_NONBLOCK)
OSError: [Errno 2] No such file or directory: '/dev/ttyS0'
```

It work when adding `+ glob.glob('/dev/rfcomm*')` to this line in **serialmanager.py**
```
glist = glob.glob('/dev/ttyACM*') + glob.glob('/dev/ttyUSB*') + glob.glob('/dev/rfcomm*')
```

**Comment by astagi** [comment]
Thanks :) :)

It looks you're not passing connection to your DallasTemperature object, it should be:

    connection = SerialManager('/dev/rfcomm0')
    sensors = DallasTemperature(2, connection=connection)

**Comment by astagi** [comment]
@Pi3R1k in case it works with the ''connection'' parameter please close this issue :) and again thank you for contributing to Nanpy :smiley: :smiley:

**Comment by Pi3R1k** [comment]
Thank you to provide Nanpy ! I just help to improve a great project i like to use. ;)

"connection" parameter work.

I have just a last problem with bluetooth. When i stop a python script when it's requesting or getting data my arduino freeze and i need to do a hard reset to connect again.

**Comment by Pi3R1k** [comment]
You can close. 
I reset with watchdog but i had some problem with bootloader of arduino nano. After flashing optiboot bootloader : work good :)

**Comment by astagi** [comment]
Thank you @Pi3R1k :)
