### ISSUE TITLE
SerialTimeout using LCD I2C

### ISSUE THREAD

**Issue by astagi** [nanpy/nanpy#25]
Reported by Shaun Van Wyngaard 

*Code*

    I2C = True
    def hello():
        connection = SerialManager(sleep_after_connect=2)
        cols, rows = 16, 2
        if I2C:
            pins = [0x20, 2, 1, 0, 4, 5, 6, 7, 3, 0]  
            lcd = Lcd_I2C(pins, [cols, rows], connection=connection)
            lcd.setBacklight(0)
        else:
            pins = [7, 8, 9, 10, 11, 12]
            lcd = Lcd(pins, [cols, rows], connection=connection)
        lcd.setCursor(0, 0)
        lcd.printString('hello')
    if __name__ == '__main__':
        hello()

---
*Output*

    pi@raspberrypi ~ $ sudo python lcd.py
    DEBUG:nanpy.serialmanager:opening port:/dev/ttyACM1 [115200 baud]
    DEBUG:nanpy.serialmanager:sending:'Lcd_I2C\x00'
    DEBUG:nanpy.serialmanager:sending:'0\x00'
    DEBUG:nanpy.serialmanager:sending:'12\x00'
    DEBUG:nanpy.serialmanager:sending:'new\x00'
    DEBUG:nanpy.serialmanager:sending:'32\x00'
    DEBUG:nanpy.serialmanager:sending:'2\x00'
    DEBUG:nanpy.serialmanager:sending:'1\x00'
    DEBUG:nanpy.serialmanager:sending:'0\x00'
    DEBUG:nanpy.serialmanager:sending:'4\x00'
    DEBUG:nanpy.serialmanager:sending:'5\x00'
    DEBUG:nanpy.serialmanager:sending:'6\x00'
    DEBUG:nanpy.serialmanager:sending:'7\x00'
    DEBUG:nanpy.serialmanager:sending:'3\x00'
    DEBUG:nanpy.serialmanager:sending:'0\x00'
    DEBUG:nanpy.serialmanager:sending:'16\x00'
    DEBUG:nanpy.serialmanager:sending:'2\x00'
    DEBUG:nanpy.serialmanager:received:''
    Traceback (most recent call last):
      File "lcd.py", line 34, in <module>
        hello()
      File "lcd.py", line 22, in hello
        lcd = Lcd_I2C(pins, [cols, rows], connection=connection)
      File "/usr/local/lib/python2.7/dist-packages/nanpy-0.9-py2.7.egg/nanpy/lcd_i2c.py", line 13, in __init__
        self.id = self.call('new', pins, begin)
      File "/usr/local/lib/python2.7/dist-packages/nanpy-0.9-py2.7.egg/nanpy/arduinoboard.py", line 148, in call
        return _call(self.namespace, self.id, args, self.connection)
      File "/usr/local/lib/python2.7/dist-packages/nanpy-0.9-py2.7.egg/nanpy/arduinoboard.py", line 46, in _call
        ret = return_value(connection)
      File "/usr/local/lib/python2.7/dist-packages/nanpy-0.9-py2.7.egg/nanpy/arduinoboard.py", line 16, in return_value
        return connection.readline().replace('\r\n', '')
      File "/usr/local/lib/python2.7/dist-packages/nanpy-0.9-py2.7.egg/nanpy/serialmanager.py", line 96, in readline
        raise SerialManagerError('Serial timeout!')
    nanpy.serialmanager.SerialManagerError: Serial timeout!

@ponty can you reproduce this?

**Comment by astagi** [comment]
Any update there?

**Comment by ShaunVW** [comment]
I never pursued this any further after burning out my LCD. I’d love to have gotten to the bottom of this, but eventually I had to move on and hope that someone with a similar setup to me would take it further.
Sorry that there wasn’t any resolution to this.


Disclaimer

The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful.

This email has been scanned for viruses and malware, and automatically archived by Mimecast SA (Pty) Ltd, an innovator in Software as a Service (SaaS) for business.  Mimecast Unified Email Management (UEM) offers email continuity, security, archiving and compliance with all current legislation.  To find out more, visit http://www.mimecast.co.za/uem.

**Comment by astagi** [comment]
@ShaunVW as @ponty said, you should try using the Arduino environment and let us know what happens with a detailed explanation of all the steps you make. I'll close this bug for the moment.
