### ISSUE TITLE
dallastemperature with not 115200 baud 

### ISSUE THREAD

**Issue by hidaba** [nanpy/nanpy#34]
Hi,
If I a use nanpy with standard baud 115200 it works but if i set 9600 or 38400 or other don't work

port='/dev/nano'
baud=57600
connection = SerialManager(device =port , baudrate=baud)
a = ArduinoApi(connection=connection)
print "connesso"

lcd = Lcd([12, 11, 5, 4, 3, 2], [16, 4],connection=connection)
a.pinMode(8, a.OUTPUT)
a.pinMode(9, a.OUTPUT)

sensors = DallasTemperature(10)
print "dallas"

program still in sensors = DallasTemperature(10)
without error or timeout.

**Comment by astagi** [comment]
any update here?

**Comment by astagi** [comment]
You need to change your baudrate in SerialManager too

    from nanpy import DallasTemperature
    from nanpy import SerialManager

    connection = SerialManager(device='/dev/cu.usbmodem141131', baudrate=57600)

    sensor1 = DallasTemperature(4, connection=connection)
    sensor2 = DallasTemperature(5, connection=connection)

    print("There are %d devices connected on pin %d" % (sensor1.getDeviceCount(), sensor1.pin))
    print("There are %d devices connected on pin %d" % (sensor2.getDeviceCount(), sensor2.pin))
    addr1 = sensor1.getAddress(0)
    addr2 = sensor2.getAddress(0)
    sensor1.setResolution(9)
    sensor2.setResolution(12)
    while True:
        sensor1.requestTemperatures(0)
        sensor2.requestTemperatures(0)
        temp1 = sensor1.getTempC(addr1)
        temp2 = sensor2.getTempC(addr2)
        print("The temperature 1, in Celsius degrees is %0.2f" % temp1)
        print("The temperature 2, in Celsius degrees is %0.2f" % temp2)
        print("Let's convert it in Fahrenheit degrees: %0.2f" % DallasTemperature.toFahrenheit(temp1))

**Comment by leofabri** [comment]
I'm experiencing the same problem. Changing baud rate doesn't actually change dallasTemperature's baud rate

**Comment by timiona** [comment]
> Vous devez également modifier votre débit en bauds dans SerialManager
> 
> ```
> from nanpy import DallasTemperature
> from nanpy import SerialManager
> 
> connection = SerialManager(device='/dev/cu.usbmodem141131', baudrate=57600)
> 
> sensor1 = DallasTemperature(4, connection=connection)
> sensor2 = DallasTemperature(5, connection=connection)
> 
> print("There are %d devices connected on pin %d" % (sensor1.getDeviceCount(), sensor1.pin))
> print("There are %d devices connected on pin %d" % (sensor2.getDeviceCount(), sensor2.pin))
> addr1 = sensor1.getAddress(0)
> addr2 = sensor2.getAddress(0)
> sensor1.setResolution(9)
> sensor2.setResolution(12)
> while True:
>     sensor1.requestTemperatures(0)
>     sensor2.requestTemperatures(0)
>     temp1 = sensor1.getTempC(addr1)
>     temp2 = sensor2.getTempC(addr2)
>     print("The temperature 1, in Celsius degrees is %0.2f" % temp1)
>     print("The temperature 2, in Celsius degrees is %0.2f" % temp2)
>     print("Let's convert it in Fahrenheit degrees: %0.2f" % DallasTemperature.toFahrenheit(temp1))
> ```

Hello,
I'm on Spyder Anaconda (4.1.5) or Edupython (2.7)
I try your code but it doesn't work for me...
I don't know why ...

On arduino code, the function "OneWire" is used.
I don't know how use it .. 
Can you help me please ?
