### ISSUE TITLE
enable default timeout

### ISSUE THREAD

**Issue by ponty** [nanpy/nanpy#36]
currently: SerialManager(..,timeout=None)

timeout should have a default value, it can be between 1-5 sec

Reason: we got better error reports with stack from new users.

I don't know any operation in the firmware which can take more seconds other than sleep(),
but using long sleep() in the firmware  is a bad solution .

see #33

**Comment by astagi** [comment]
Work in progress, I'll work on it during this we

**Comment by astagi** [comment]
Closed by https://github.com/nanpy/nanpy/commit/2ded6d8d00938fcdb55d1f253f095b1c92fa1506
