### ISSUE TITLE
Request: Support for RS485

### ISSUE THREAD

**Issue by lunasilvestre** [nanpy/nanpy#41]
I'm working with multiple Arduini at long distances (>100m) and bumped into RS485 - affordable albeit cable based.
Any chance RS485 (or zigbee/wifi) will be supported in Nanpy?

**Comment by astagi** [comment]
I will start reading some documentation about it :) let you know

**Comment by ponty** [comment]
RS485 should work already, it has the same device in Linux as RS232.
The Nanpy communication is half duplex (master/slave), so this should not be a problem.

**Comment by astagi** [comment]
Thanks @ponty I can close this bug. @lunasilvestre try Nanpy with RS485 and let us know :)
