### ISSUE TITLE
Release 0.9.3

### ISSUE THREAD

**Issue by astagi** [nanpy/nanpy#44]
Nanpy 0.9.3 will be released next week, before 18 Feb. 2015.

@ponty have you anything pending that you want to see merged in 0.9.3 release?

**Comment by ponty** [comment]
Nothing special. I added Landscape.io badge, and fixed some warnings.
But I don't change the code until next release.

**Comment by astagi** [comment]
@ponty I'd like to freeze 0.9.3 on https://github.com/nanpy/nanpy/commit/5f574cb67a99b5d53d01b69f3d027c69c94eb2c0

Is it ok for you? anything pending?

**Comment by ponty** [comment]
OK!

**Comment by astagi** [comment]
Completed! :) :) :+1: :+1:
