### ISSUE TITLE
How can I detach a servo?

### ISSUE THREAD

**Issue by dankozlowski** [nanpy/nanpy#70]
I have a couple of servos that need to remain open for an hour or so, and I'd like to disconnect them from their pins while they stay open.  Is there a way to do this with Nanpy?  I see a method to check Servo#attached and that #attach and #detach are implemented in the Firmware, but I can't seem to get attach or detach to work in Python.

**Comment by omn0mn0m** [comment]
I know this is an old issue, but write this into servo.py:

```python
@arduinoobjectmethod
    def detach(self):
pass
```

Not sure why it is not in already.

**Comment by dankozlowski** [comment]
Oh my God.  You wanna open a PR or shall I? :P

Thanks!

**Comment by omn0mn0m** [comment]
Wait, did no one figure out this was missing...

**Comment by ponty** [comment]
Merged.
