### ISSUE TITLE
Soft-reset nonfunctional.

### ISSUE THREAD

**Issue by dankozlowski** [nanpy/nanpy#72]
Following the example, my code fails as following:

```
Traceback (most recent call last):
  File "00000000911c3aa3_relay.py", line 10, in <module>
    a.soft_reset()
AttributeError: 'ArduinoApi' object has no attribute 'soft_reset'
```

**Comment by ponty** [comment]
There should be no such problem if you try the latest version.
Example program: examples/reset.py

There is an other problem: watchdog doesn't work with some bootloaders.
Soft_reset() is based on watchdog.

http://arduino.stackexchange.com/questions/2922/watchdog-timer-stuck-in-restart-loop-green-led-flashing
"The OP is using an Adriuni Pro Mini clone. The included bootloader on the Arduino Pro Mini does not support system restarts by the WDT. Essentially, on a device with a bootloader that does not support WDT restarts, the board will restart but the timer / reset will not causing the board to continuously reset on reboot. There are alternative bootloaders for arduino boards that may resolve this issue."
