### ISSUE TITLE
Interrupts 

### ISSUE THREAD

**Issue by cheragnb** [nanpy/nanpy#75]
Is there any library to enable a timer interrupt from either the Arduino or the raspberrypi ?

**Comment by ponty** [comment]
Please write some details. What is it used for?

**Comment by cheragnb** [comment]
A nanpy or similar port for a library such as timerOne. Where i can trigger an interrupt every 100 milliseconds. 
For me particularly im controlling a robot from a raspberry pi via an arduino. I need to update certain sensor values almost continuously (every 200 ms)

**Comment by cheragnb** [comment]
I found a way to use interrupts, rather than interrupting the arduino, interrupt PYthon to updat eyour wrapper. 

def interrupt():
    threading.Timer(time_between_calls, interrupt).start()

make sure to include threading,time

**Comment by ponty** [comment]
https://apscheduler.readthedocs.io/en/latest/

"Advanced Python Scheduler (APScheduler) is a Python library that lets you schedule your Python code to be executed later, either just once or periodically."

**Comment by ponty** [comment]
Timer interrupt is not possible in nanpy firmware but it is possible in python.
