### ISSUE TITLE
Analog and digital pins together 

### ISSUE THREAD

**Issue by cheragnb** [nanpy/nanpy#76]
Hi, Im using NANPY to controll an Arduino as a slave. My project requires me to use ALL the arduino pins. 

How does the system differentiate between 

a.analogRead(A4)
and 
a.digitalWrite(4)

where A4 is the analog in pin and 4 is the digital out pin. Apparently nanpy doesnt consider A1,A2 etc as valid pin values.

Thanks!

**Comment by cheragnb** [comment]
my mistake. got it 
#20

**Comment by KerwynLim** [comment]
Hey sorry , what was the solution for this i'm trying to figure it out however i couldn't find a solution

**Comment by manavmehraa** [comment]
Could someone post the solution please? Is A0 pin 14 ?
