### ISSUE TITLE
Stepper module potentially incorrect

### ISSUE THREAD

**Issue by dankozlowski** [nanpy/nanpy#96]
The Stepper example has a stepper with two leads -- I'm not sure that exists.  Which types of steppers are to be used with Nanpy, and what does the wiring look like?

**Comment by dankozlowski** [comment]
Is it meant for something like this?

https://www.pololu.com/product/2980

**Comment by ponty** [comment]
Nanpy has only a wrapper for Arduino Stepper library:
https://www.arduino.cc/en/Reference/Stepper

Your questions are about Arduino not Nanpy.
So first try to test Stepper without Nanpy, using only Arduino code.

**Comment by dankozlowski** [comment]
Gotcha, thanks for the response.  I ended up just going with a controller, which has worked perfectly for my needs.
